import Head from 'next/head';
import {
   Select,
   Input,
   InputLeftAddon,
   InputGroup,
   VStack,
   Button,
} from '@chakra-ui/react';

export default function Home() {
   return (
      <>
         <Head>
            <title>SJ Pickup Soccer</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/World cup icon.png" />
         </Head>

         <VStack justifyContent="space-around" background="/World cup icon.png">
            <h1>Welcome to South Jersey pick-up soccer</h1>
            <p>
               Please fill out the form to play in the next available session!
            </p>

            <InputGroup flexDir="column" w="auto" color="white">
               <InputLeftAddon bg="rebeccapurple">Your Name</InputLeftAddon>
               <Input type="text" placeholder="Name" bgColor="gray.500" />
               <br />
               <InputLeftAddon bg="rebeccapurple">Date</InputLeftAddon>
               <Input type="datetime-local" bgColor="gray.500" />
               <br />
               <InputLeftAddon bg="rebeccapurple">Position</InputLeftAddon>
               <Select w="sm" bgColor="gray.500">
                  <option value="FW">FW</option>
                  <option value="RW">RW</option>
                  <option value="LW">LW</option>
                  <option value="CAM">CAM</option>
                  <option value="CDM">CDM</option>
                  <option value="CM">CM</option>
                  <option value="RB">RB</option>
                  <option value="LB">LB</option>
                  <option value="CB">CB</option>
                  <option value="GK">GK</option>
               </Select>
            </InputGroup>
            <Button bgColor="rebeccapurple" color="white">
               Submit
            </Button>
         </VStack>
      </>
   );
}
